### Obtener las peliculas
GET http://localhost:1234/movies

### Obtener las peliculas por Id
GET http://localhost:1234/movies/3c4595a6-d0fc-44a1-bdfe-7ecae0fa7dc7

### Obtener las peliculas por genero
GET http://localhost:1234/movies?genre=Drama

### Crear una pelicula
POST http://localhost:1234/movies
Content-Type: application/json


{
  "title": "The Shawshank Redemption 3",
  "year": 1994,
  "director": "Frank Darabont",
  "duration": 142,
  "poster": "https://i.ebayimg.com/images/g/4goAAOSwMyBe7hnQ/s-l1200.webp",
  "genre": [
    "Drama"
  ]
}

### Actualizar una pelicula
PATCH  http://localhost:1234/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3
Content-Type: application/json

{
    "year": 1993
}